#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ZOUIPOCAR_PORT 1234

#define ZOUIPOCAR_TIMESTAMP_OFFSET 0
#define ZOUIPOCAR_TIMESTAMP_SIZE 4

#define ZOUIPOCAR_LATITUDE_OFFSET 4
#define ZOUIPOCAR_LATITUDE_SIZE 4

#define ZOUIPOCAR_LONGITUDE_OFFSET 8
#define ZOUIPOCAR_LONGITUDE_SIZE 4

#define ZOUIPOCAR_SPEED_OFFSET 12
#define ZOUIPOCAR_SPEED_SIZE 1

#define ZOUIPOCAR_PACKET_SIZE 13

#endif // CONSTANTS_H
